### ISSUE TITLE
sometime the test case "search_radius_returns_correct_item" will fail

### ISSUE THREAD

**Issue by damody** [adnanademovic/rust-flann#1]
```
---- tests::index::search_radius_returns_correct_item stdout ----
        thread 'tests::index::search_radius_returns_correct_item' panicked at 'assertion failed: `(left == right)`
  left: `[0, 1, 3, 4, 5, 6, 7]`,
 right: `[0, 1, 2, 3, 4, 5, 6, 7]`', src/tests/index.rs:205:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: flann::tests::index::search_radius_returns_correct_item
             at src/tests/index.rs:205
   8: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1480
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/libtest/lib.rs:141
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99


failures:
    tests::index::search_radius_returns_correct_item

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by adnanademovic** [comment]
Hmm then I guess the test is flaky. I'll reduce the number of tests for that. The test is there just to check if the interface is correct, since FLANN's functionality is outside of my hands, obviously.

**Comment by vadixidav** [comment]
I ran into this issue as well, but I think the test was just incorrect. See my PR #3. Tests are working consistently in there.
